var express = require("express");
var path = require("path");
var cookieParser = require("cookie-parser");
var logger = require("morgan");
var app = express();

// Database related things 
const mongoose = require("mongoose");
const session = require('express-session');
const MongoDBStore = require('connect-mongodb-session')(session);
const MONGODB_URI = "mongodb+srv://arnobkumarsaha:sustcse16@cluster0.nj6lk.mongodb.net/myDatabase?retryWrites=true&w=majority";

const csrf = require('csurf'); // to prevent csrf attack
const flash = require('connect-flash'); // to help users by showing what error occured.

// only require related things above.
// _____________________________________________________________________________________________________________

app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");

// generated by express itself
app.use(logger("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, "public")));


// Specifying the session storage & then use the middleware
const store = new MongoDBStore({
  uri: MONGODB_URI,
  collection: 'sessions'
});
const csrfProtection = csrf();


// session, crsf(cross site request forgery) & flash Middlewares
app.use(
  session({
    httpOnly: false,
    secret: 'my secret',
    resave: false,
    saveUninitialized: false,
    store: store
  })
);
//app.use(csrfProtection);
app.use(flash());

// Check if the requester is authenticated or not
const checkType = require('./util/checkTypeOfUser');
app.use(checkType);

// isLoggedIn, user and typeOfUser of req.session are set in postLogin of authController
// But Note that , req.user is set in the above middleware.
// res.locals variables are passed to every views.
const setLocals = require('./util/setReqLocals');
app.use(setLocals);


// Middleware related things above.
// _____________________________________________________________________________________________________________

// import Routes
var indexRouter = require("./routes/index");
var userRouter = require("./routes/user");
var adminRouter = require("./routes/admin");
var studentRouter = require("./routes/student");
var teacherRouter = require("./routes/teacher");
var authRouter = require("./routes/auth");

const errorController = require('./controllers/error');

// Register routes

// only / , which renders the profile. (can redirect to /login) Also userType distribution will occurred here.
app.use("/user", userRouter); 

// /add-teacher, /teachers, /edit-teacher/:teacherId, /delete-teacher
// /add-course, /courses, /edit-course/:courseId, /delete-course
// /students
app.use("/admin", adminRouter);

// Going to work in these two.
app.use("/student", studentRouter);
app.use("/teacher", teacherRouter);

app.use("/", indexRouter); // only / , redirect to /user
app.use(authRouter); // /login, /signup-student, /signup-teacher, /logout


// If all the above routes failed..
app.use(errorController.get404);

// SideNote: views er attribute name gulu hoilo req.body.  url er '?' mark er aager gulu req.params, porer gulu req.query

// Connect to DB on port 3000.

mongoose
  .connect(
    MONGODB_URI,
    {
      useUnifiedTopology: true,
      useNewUrlParser: true
    }
  )
  .then(result =>{
    app.listen(3000);
    console.log("Yesss. MongoDB connected !!      Listening on port 3000.");
  })
  .catch(err =>{
    console.log(err);
  });


module.exports = app;
